### ISSUE TITLE
Record YouTube video titled: How to get a job as a full-stack developer

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#1845]
- [ ] Write script
- [ ] Create slides
- [ ] Create worksheet
- [ ] Record Video
- [ ] Edit video
- [ ] Upload video
- [ ] Create blog post out if it
- [ ] Promote video/post (quora, LinkedIn, Medium, social media, email list)

Are you a full-stack developer looking for an awesome job at a great company?

In this video, I’ll explain the best way to get hired as a developer.

* Step 1: Polish your resume
    * Optimize keywords
    * Include the job title you’re applying for
    * 3-5 quantifiable bullets per job position
        * Key achievements - show you’re employer why you’re an awesome fit
        * Don’t list duties but accomplishments
        * Make each bullet point specific and data-driven
            * Ie: X result from doing Y or, from doing Y I achieved X result
            * If you don’t have data then be specific
            * Problem solving abilities and abilities to save/earn the company money
    * Put your education AFTER your work experience
        * Below your name if you have a PhD or attended a top university
        * At the bottom of the resume if it’s a mid tier education (estate school)
        * Don’t put your GPA unless is both recent and high (over 3.5)
    * Don’t ignore unpaid experience
        * List any unpaid projects/jobs which experience is relevant to the job
    * Keep it all to 1 page max
        * You only have 6 seconds to make an impression
        * Only out relevant experience from the last 3-5 years
        * Put most relevant experience first
    * Don’t include an objective
        * It’s redundant. Employers care what you can offer not what you want
        * Include a short paragraph with the highlights of your career and achievements
    * Avoid generic skills
        * Skills like; leadership, project management, detail oriented, hard-working, good communications skills
        * Include hard evidence and facts that proof that demonstrate your skills
        * Only include skills and achievements that are relevant to the job or make you look outstanding (won Nobel Prize)
    * Avoid Spelling Errors
        * Get resume reviewed (career counselor, Grammarly)
    * Taylor your resume to each position you apply
        * It will increase your chances to get noticed
        * It will show employers you’re not lazy and willing to go above and beyond
        * Show strong work ethic
        * Ability to solve problems independently
        * Culture fit
    * Have you own website to showcase your work and personality
        * Get your own name as a domain name (Hover, Namecheap)
* Step 2: Polish your Linkedin Profile
    * From Linda Rayner: https://www.youtube.com/watch?v=27BTcka64wQ
    * Tip #1 - Have a Photo that Sends Good Vibes 
    * Tip #2 - Use an Appropriate Headline 
    * Tip #3 - Have a “What I Can Do for You” Oriented Profile Summary
    * Tip #4 - Make Your Work experience Short & Sweet
    * Tip #5 - Show off Your Recommendations 
    * Tip #6 - Contact Details
    * From John Marty https://www.youtube.com/watch?v=_NkBkCgexPc
    * Complete 100% of your profile → get to All Star
    * Put your title on the headline so recruiters can find you
    * Use Snapper or Photofeeler to rate the quality of your profile photo
    * Make your profile summary short, sell yourself, make it mobile friendly
    * If you’re older than 30 yo you should have 500+ connections
    * Try to get connections at the companies you’re applying to
* Step 3: Polish your Github account
    * From Quora: https://www.quora.com/What-do-employers-like-to-see-in-someones-GitHub-account-Do-they-look-at-style-projects-frequency-etc
    * Are the projects well organized...by looking at the directory structure naming, can I get a sense of the architecture/design - it is easy to figure out where to go in the project to locate the various functional areas and layers.
    * Is the code clean, easy to read and commented appropriately.
    * Is there an organized branching/tag process being followed, e.g. gitflow
    * Is there some sense that the person understands basic design patterns.
    * Does the project leverage existing open source libraries and frameworks (good) or does the code re-solve common problems/routines (bad)
    * Does the first thing I see (the README) clearly describe the project e.g. what it does, how to run and build it etc.
    * Do I see replicated code i.e. do I see obvious 'cut and paste' and 'repeating myself' code (bad)
    * ARE THERE TESTS!!!! There should be a test harness and if I run it (because the README told me how to run them), the tests should pass. This is a big one for me. If I don't see tests, the very first question I will ask will be 'how do/did you test this code' and your answer will be 'manually' which of course means you don't test!! IMO, professional quality code includes some level of unit/integration testing delivered along with it.
    * I am less concerned with what the project does, more concerned that it was developed 
    * Signs of recent activity
    * A bunch unmodified forks of common open-source projects
    * The same coding tutorials as everyone else in your graduating class (e.g., the Javascript Snake game, ActiveRecord Lite, etc.) -- remember: your entire class is sending out resumes/applications at the same time, often times to the same companies, so reviewers will notice those same repos!professionally. I look for commercial quality code...will others be able to take the project and easily enhance/maintain it.
* Step 4: Practice Interview questions in English
    * https://www.themuse.com/advice/how-to-answer-the-31-most-common-interview-questions
    * Research Interview questions on GlassDoor
        * If we were to contact a past supervisor and asked them to rate your performance at a previous position, what would they say?
        * What are some failures in your life and how did you deal with them?
        * What would your team say is your superpower?
        * What is your cryptonite?
        * What were you grades like in University?
        *  what do you not want to do in your next job?
        * Where do you see yourself in five years?
* Step 5: Practice coding interview questions
    * Coding Questions Online Training
        * https://leetcode.com/
        * https://codefights.com/interview-practice
        * https://www.interviewbit.com/
        * https://www.hackerrank.com/programming-interview-questions/
        * https://www.byte-by-byte.com/coding-interview-questions/
    * Research Interview questions on GlassDoor
* Step 6: join Hackathons
* Step 7: network, network, network
* Step 8: Learn to market yourself
  * Remember you're a product and employers are looking to buy the best products
  * In a sea of competition you need to lear to stand out
  * Lavalife story: record a video, show personality, 
  * Offer something for free: Grumo Media story
  * Look different: V-Necks, hair-dos, brand yourself.
  * Develop an unrelated unique skill: beat boxing at Drive Digital
* Step 9: Research the top companies hiring
    * Find jobs at Indeed, Ziprecruiter, Angel.co, Google Jobs
    * Research companies
        * GlassDoor, Their blog, reviews, Crunchbase, Wikipedia
        * Pay most attention to longer well written reviews (See Hootsuite)
* Step 10: Apply to jobs!
    * It shows you care more if you apply directly via the company website
    * Recruiters will help but it shows less commitment from the candidate
* Bonus: Join Mench 8-week job placement bootcamp at https://mench.com/gethired

**Comment by shervine** [comment]
Not working on this as we now will focus on companies as our primary customer
