### ISSUE TITLE
Explore Linkedin Recruitment as a Lead Channel

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2018]
@grumo I think we can find a way that gives us access to a large market of junior developers through Linkedin to build out top funnel.

> A premium plan for hiring specialists, known as Recruiter Lite, is $119.99/month. (LinkedIn also offers a full-strength package for recruiters, sold separately by its Talent Solutions division.) On all plans, customers buying annual subscriptions qualify for slight discounts.

Thoughts?

**Comment by grumo** [comment]
Closing for now as not related to top priority of getting companies to use Mench as a candidate selection tool.

**Comment by shervine** [comment]
@grumo we should remove ourselves from the issues that we are closing without completing so we can identify issues that are complete without any execution. Basically, any issue that is closed without anyone assigned to it means that we later decided not to work on it... I will remove you from this one, and you can do this for all future issues like this...

**Comment by grumo** [comment]
@shervine got it. I'll do so from now on.
