### ISSUE TITLE
Capture student multi-media answers right from Messenger such as Text, Audio, Video, Images

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2069]
@shervine Right now students can only submit long form answers or URLs to Intents that require so from the Action Plan.
It would create a much more fluid experience if those answers could be captured right from Messenger.

Here is how the workflow could go:

Mench: Answer the question "How has a failure, or apparent failure, set you up for later success?"
Mench: [\Answer] [\Skip]

Student: \Answer

Mench: Great! Just type your answer and press Send
Mench: You can also send a picture, record an audio clip, or send a video.
Mench: [\Ok. Continue]

Student: Recently, failure to get a promotion led to me defining a role with a bit of a personal work mission, and led to 18 months of the best work I’ve done.

(student presses Send on Messenger)

Mench: Are you happy with your answer?
Mench: [\Yes. Submit] [\Yes. Add More] [\No. Change] [\Cancel]

Student: \Yes. Add More

Mench: No problem. Just add more to your answer and press Send.
Mench: [\Ok. Continue]

Student: (Audio file uploaded)

Mench: Great! Are you happy with your answer now?
Mench: [\Yes. Submit] [\Yes. Add More] [\No. Change] [\Cancel]

Student: [\Yes. Submit]

Mench: Fantastic! You're answer has been submitted.

**Comment by shervine** [comment]
This is done as part of #2035
