### ISSUE TITLE
Launch Mench contest to grow audience

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2073]
@shervine I'd like to organize a joint contest with my contact Sebastian Marshall. The contest would be for junior developers and they would win the top 5 essential programming books and a resume optimization session. 

Sebastian ran a contest last month for his audience (tech entrepreneurs, coders) and was able to add over 1000 new subs to his list. He agreed to handle the logistics and share the cost of the prize (under $200). He needs for us to complete the following items before running it ideally next Monday (Cyber Monday)

- [ ] Come up with a title for the contest: ie: Wind the essential started packacke for Junior programmers.
- [ ] 1-paragraph description of the contest and why coders should join.
- [ ] List of exact books, tools, prizes (totalling less then $200)

**Comment by shervine** [comment]
Our strategy for early adopters will be via free job boards which we've already tested
