### ISSUE TITLE
Create Mench videos for Miners

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2128]
- [ ] What is Mench
  - [ ] What problem Mench is solving
  - [ ] Why now?
  - [ ] What's Mench ultimate vision?
  - [ ] How it works overview
- [ ] Understand basic terminology of Mench
  - [ ] What is a Miner?
  - [ ] What are Intents?
  - [ ] What are Entities?
  - [ ] What is the Ledger?
- [ ] What is Mench first focus?
- [ ] Why are we focusing on helping Junior developers find great jobs?
- [ ] How do Miners make money?
- [ ] Why would someone become a Miner?

**Comment by shervine** [comment]
Not working on this as we now will focus on companies as our primary customer
