### ISSUE TITLE
Enter all coding interview sources for mining

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2137]
Source of links: https://docs.google.com/spreadsheets/d/1lqRKKPK5TUwky351jbTSDqCQt4Dp-LPdSdKSniJkt14/edit#gid=0

**Comment by shervine** [comment]
@grumo I finished double checking all entered sources, including the hackathons, and we're now ready to focus on the next stage: Intent/message mining from within expert sources.

**Comment by shervine** [comment]
@grumo FYI we've currently mined only 7.3% of our 369 sources: https://mench.com/ledger

**Comment by grumo** [comment]
@shervine this is going to be an exciting challenge as we uncover the principles of optimum knowledge mining!
