### ISSUE TITLE
Apply YCombinator Summer 2019 Batch

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2196]
Deadline: 8pm on March 25th, 2019
Apply as non-profit here: https://apply.ycombinator.com/app/edit?apptype=nonprofit

**Comment by shervine** [comment]
@grumo Totally agree with you, let's do it!

**Comment by shervine** [comment]
@grumo Any updates on this? I can help with an iteration once you have the first draft ready

**Comment by grumo** [comment]
@shervine not yet. Aiming for Monday to have it.

**Comment by shervine** [comment]
@grumo Ping me when ready and I can have a look. The deadline is Monday too! You wanna move our working session next week from Tuesday to Monday so we can iterate your first draft together?

**Comment by grumo** [comment]
@shervine I'm ok to move to Monday but remember that they accept late applications way past the deadline. Last time I applied two weeks from their interviews and they flew me there!

**Comment by shervine** [comment]
@grumo If Monday works for you then let's do it cuz it would not hurt to be on-time. I'll update the calendar invite

**Comment by shervine** [comment]
@grumo I completed my founder profile but I do not see our application yet...
