### ISSUE TITLE
Ping other Miners to Collaborate

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2200]
Since a single person would not be able to publish content on Mench as everyone would require at-least 1 other person to review/iterate their work, we can add a feature to "Ping" another miner to a particular intent/entity to have it published. It's a communication tool that would help miners use each other's help to publish content to Mench.

Workflow:

1. Miner mines intents/messages they want to mine
2. Once they feel ready for review, they would ping either a specific miner or "any" miner and Mench personal assistant would send a message to miners to notify them about the intent/message that needs attention
3. The second miner loads up the intent, does the review, iterates the content if needed, and then changes the status by 1 level. Note that there is a special permission called "[Double Status Level-Up](https://mench.com/entities/6084)" which if set to a miner, would allow them to change the status of New to Published if they deem the intent is ready to go live. They can also choose to level-up by one (new to drafting) and then have some other miner (could be the original author again) do another review/iteration and then level-up from drafting to published.

The idea is to create a step-by-step inter-dependancy workflow designed around the principles of collaboration.

@grumo Thoughts?

TODO

- [ ] Ping feature to notify miners of a new message/intent: In some cases when we add a new intent note or modify an intent/entity we'd want a specific Miner to know about it. The /ping command can notify the pinged entities about the changes.

**Comment by grumo** [comment]
@shervine I am still not sure we need the status New. It would make more sense to just have Draft and Published only. Any new intents/messages would automatically be in Draft mode and could be searched by recency. Miners could simply load all draft messages and review those for where the review request was made. We can discuss further on Tuesday.

**Comment by shervine** [comment]
@grumo I think we need 3 statuses on the student side Action Plan because some "steps" are new (not started at all), some are "working on/drafting" (because they have started a child step but have not yet finished the parent step), and some are published/done as the entire tree is done. For these terminologies, we'd also have to consider the student side, which for them something like new/working-on/done makes more sense than new/drafting/published. Not sure if we can find a middle-ground terminology, or I can implement different terms for each side. We can talk more tomorrow.

**Comment by shervine** [comment]
Related to #2214
