### ISSUE TITLE
Rename Mench Coins to Mench Points

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2215]
@grumo Since the coins would not have any monetary value for the foreseeable future, I think we want to be careful with the terminology we use to not build any false expectations. In fact, we should not ever pitch "making money" as a motivator for new miners since we're a new platform and our financial model is yet to be validated.

For this reason, I suggest renaming Mench Coins to Mench Credits to focus on the idea that we're only trying to give an approximate credit to miners based on the transactions they mine.

Thoughts?

**Comment by grumo** [comment]
@shervine Agree on avoiding the term coin/money for now. Consider also "points", "karma", or "reputation". In our case I like "points", it sounds more game-like.

Refs:

- Reddit uses karma: https://www.quora.com/What-is-Reddit-karma-and-how-do-people-benefit-from-having-more-of-it
- StackExchange uses reputation: https://stackoverflow.com/help/whats-reputation

**Comment by shervine** [comment]
@grumo Yea I agree, we can discus this more during our next meeting to set the replacement term and I will then update the platform

**Comment by shervine** [comment]
This is now live
