### ISSUE TITLE
Create list of LA tech recruiters

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2251]
Google List -> [HERE](https://docs.google.com/spreadsheets/d/1B1Bh1PPDlLE0RJT2uZE3F2haotohMTHpADm-FnOeKPE/edit#gid=0)
- [ ] Create list of ~50 top tech recruiters in LA
 - https://www.yelp.com/search?find_desc=tech+recruiters&find_loc=Los+Angeles%2C+CA
- [ ] Connect to find out if they have referral programs
- [ ] If they do, find out how their programs work

Textrecruit - AI recruiting over SMS -> https://www.textrecruit.com/staffing/

**Comment by grumo** [comment]
Closing for now as not related to top priority of getting companies to use Mench as a candidate selection tool.

**Comment by shervine** [comment]
@grumo Also removed you from this one as it was not executed on...
