### ISSUE TITLE
MVP Day 4: Invite candidates & test platform

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2271]
- [x] Miguel: compose [invitation email](https://docs.google.com/document/d/1CisKdFGWJtQ_eF26D2afCtMXiI7TKl419PQ8UXI8gp0/edit#) for Indeed applicants
- [x] Schedule invitation to be sent via MailShake

**Comment by shervine** [comment]
@grumo This was just done woooot wooooot
