### ISSUE TITLE
MVP Day 3: Finish Assessments and Invite Candidates

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2274]
- [x] Miguel: Add Routing results to all assessments as: https://mench.com/intents/7902
- [ ] Miguel: Invite 500+ candidates to Mench assessment
- [ ] Shervin: Finish intent routing logic
- [x] Get Indeed referral link ([$2,000 USD if hired via link](https://prime.indeed.com/refer#/candidateReferral)) -> https://prime.indeed.com/refer/c-Js1Kpp6?sid=primeref&kw=employer_0bf30a89692a0cb4
- [ ] Explain in messages available Messenger: - I want to, next, stats
- [ ] Explain also how to access Messenger persistent menu

**Comment by shervine** [comment]
We do have 500+ in line now
