### ISSUE TITLE
Convert single character or emoji of OR children to buttons on Messenger Personal Assistant

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2285]
When all children of an OR intent have a single character or emoji convert them to buttons and don't list them
- [ ] Create function to detect emojies from an array containing most widely used emoji codes
- [ ] This would be very useful for Yes/No answers as well. ie: Convert Yes and No children to Yes/No buttons automatically.

Sample use case: to rate images with emojies instead of boring numeric buttons

**Comment by shervine** [comment]
Good one
