### ISSUE TITLE
Notify students when top intent is completed

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2290]
When a student completes the last intent of a top intention (ie: Learn Mench Intent mining principles) send them a message like: "Congrats! you've completed your intention to Learn Mench Intent mining principles. You have 2 intentions left in your Action Plan."

**Comment by shervine** [comment]
This requires Log User Intention Completion History V1 #2478

**Comment by shervine** [comment]
Merging into Notify users when they are switched to resume another top intent #2365
