### ISSUE TITLE
Intent Filters V1

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2319]
Based on our recent pivot to #2318 we want to create an alternative view of the intent browser to be used by company HR staff to browse candidates and merits and filter/unlock the top-matching candidates.

TODO

- [x] Filter by user & date range

**Comment by shervine** [comment]
@grumo This is now in place which enables you to filter the intent tree by user or date range or both. Here is an image of how to access the new filters:

![Capto_Capture 2019-05-26_06-28-48_PM](https://user-images.githubusercontent.com/3269798/58390079-3b8edc00-7fe4-11e9-9f61-d56536e4a588.png)

**Comment by grumo** [comment]
@shervine this is great! I tried it but the only problem is when I click the red flag button after applying a filter I still can see all the users, not just the filtered ones.

**Comment by shervine** [comment]
@grumo This is now updated with a separate list for matching users
