### ISSUE TITLE
White-Label Referral Engine V1

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2326]
We want a system where a landing page can be loaded with a specific referral ID that would log that candidate to the target referral entity (The company) so they get to unlock those students for free.

- [x] Special format URL that includes entity referral ID as follow: mench.com/ENID_INID
- [x] White-label landing page with minimal mench logo and focus on referral
- [x] Support referral on Messenger ref variable to add candidate as the child of the company based on #2325 

This would give them access to unlock candidatres via #2319

**Comment by shervine** [comment]
@grumo We have our white-label landing page ready for companies, which can use this OR a direct link to messenger to send their candidates to:

https://mench.com/7345_10707 OR https://m.me/askmench?ref=GETSTARTED_7345_10707

Another example:

https://mench.com/7345_8000 OR https://m.me/askmench?ref=GETSTARTED_7345_8000

We will give them both link options and they can choose which one to share with their candidates, but both will assign the new user to the companies entity (in this case Airbnb) which gives them free and unlimited access to the user's test results.

**Comment by grumo** [comment]
@shervine this looks fantastic! How do we create this custom white label pages?

**Comment by shervine** [comment]
@grumo Just replace the first number with the entity ID and the second number with intent id:

https://mench.com/7345_10707

**Comment by grumo** [comment]
@shervine got it
