### ISSUE TITLE
Create Mench "How it works" tree for Companies

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2329]
[This tree](https://mench.com/intents/12238) will explain to companies how Mench can automate their recruitment funnel.
It should explain how Mench works in 3 steps:

1. We create a custom assessment from a job posting they send us
2. They promote the job posting with a (trackable) link to the custom assessment
3. They pick the top performers and call them for an interview

It's free for all candidates that apply using their custom link.
They pay to contact any candidates that come from elsewhere (ie: our channels, other company job postings)

- Articles on recruitment to use as inspiration for sales copy:
- [ ] [2019 Hiring Statistics, Trends & Data: The Ultimate List of Recruitment Stats](https://jobbatical.com/blog/hiring-statistics/)
- [ ] [How advancing women’s equality can add $12 trillion to global growth](https://www.mckinsey.com/featured-insights/employment-and-growth/how-advancing-womens-equality-can-add-12-trillion-to-global-growth)
- [ ] [60 Hiring Statistics You Need to Know](https://www.ebiinc.com/resources/blog/hiring-statistics)

**Comment by shervine** [comment]
Related to #2318

**Comment by shervine** [comment]
We're done with this for now:

https://mench.com/intents/12238

It would continue to iterate from here...
