### ISSUE TITLE
Mench Career Accelerator Intro Video V1

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2350]
With some inspiration from Outco (see [their video](https://vimeo.com/229784053)), we want to create our first intro video that explains the Mench platform for software engineers.

TODO

- [ ] Write script
- [ ] Find affordable animator
- [ ] Make video :)

**Comment by grumo** [comment]
@shervine closing for now as not related to top priority of getting companies to use Mench as a candidate selection tool.

**Comment by shervine** [comment]
@grumo I will keep this one open as we'd need to tackle it once we shift focus on the user side again... I think this is a low hanging fruit in terms of content production for users...

**Comment by shervine** [comment]
Not working on this as we now will focus on companies as our primary customer
