### ISSUE TITLE
Recommend Users to Follow Mench on Social Media?

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2368]
@grumo I was thinking at the end of the assessment we can invite users to follow Mench on popular social media channels by asking them what social media channel they use and based on their answer recommending them our URL to connect...

**Comment by grumo** [comment]
@shervine good idea. I'm also planning to send all candidates a thank you email for applying and will include our social media links for them to follow our adventures.

**Comment by grumo** [comment]
@shervine to keep it simple I added the invitation to follow our progress after the thank you message as in https://mench.com/intents/9840

**Comment by shervine** [comment]
@grumo The way you did it was very hacky and did not allow users to click and follow. I updated the message by simply referencing the Mench entity which also lists all social links for users to easily click on. Checkout: https://mench.com/intents/9840#intentnotes-9838

**Comment by shervine** [comment]
And then go to the on-complete messages

**Comment by grumo** [comment]
@shervine sent you an audio explaining the previous choice. In essence, it is a better user experience to send 3 short links and still being able to see the Thank You Gif than 7 independent links which feel overwhelming and take away from the Thank You message.

3 Short Links (Thank You message still visible):
![IMG_5994](https://user-images.githubusercontent.com/7246512/58360869-e74af700-7e3f-11e9-9c32-020737f57305.PNG)

7 Links  (Thank You gone):
![IMG_5995](https://user-images.githubusercontent.com/7246512/58360865-def2bc00-7e3f-11e9-8930-9ba9fb05ce73.PNG)

**Comment by grumo** [comment]
@shervine wrote new mining principle regarding optimum number of characters to be delivered at once at #2380

**Comment by shervine** [comment]
@grumo I created a new entity for [Mench on Social Media](https://mench.com/entities/7146) which only has those 3 links
