### ISSUE TITLE
Write Mench Platform overall description

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2369]
Goal: to produce a Wikipedia-like document describing the entire Mench platform
Document: https://docs.google.com/document/d/1urVNKJ-ZpOhftug-0VwITHd-qxT9262uHVjNAJHh_lI/edit#

**Comment by shervine** [comment]
@grumo Great job on this document. We can keep expanding upon this as we roll-out our MVP for partner employers and work towards stabilizing the platform.

**Comment by shervine** [comment]
We can gradually iterate on this as we move along
