### ISSUE TITLE
Change message when uses says "Cancel"

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2372]
Right now, after pressing "Cancel", the message says :

> Ok, so how can I help you land your dream programming job?

It should be more generic as the user current top intention may be different. Here is what it could say:

> Ok, so how can I help you move forward?

-----
Issue found at the end of this user message thread [HERE](https://business.facebook.com/askmench/inbox/10106676829063112/?notif_id=1558424202507008&notif_t=page_message&mailbox_id=381488558920384&selected_item_id=100001344933902)

**Comment by shervine** [comment]
@grumo good call, I updated this and pushed live
