### ISSUE TITLE
Update Intent Mining Principles & Tweak Messages

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2377]
Based on this landing page:

https://mench.com/8417

We need to make the following adjustments:

- [X] Principle: Never replicate variables stored in the Mench Platform, like conditional step percentage min/max values. This is done here, which we can remove.
   - [x] Add above principle to intent mining principles tree ([done](https://mench.com/intents/10868))
- [x] Instead of percentage ranges, offer a description of each level and what it means in 1-2 short sentences. This could even be more helpful than the percentage ranges as those don't really mean much.
- [x] Remove all other instances where we mention the percentage range in messages and replace with a description of each level (as I think there are more intents with this type of messages)

**Comment by grumo** [comment]
@shervine I completed all the items above except adding descriptions to each level since the Beginner, Intermediate, Expert, Superstar levels are universally understood. The descriptions would add complexity and messages to explain each level.

**Comment by shervine** [comment]
@grumo yea makes sense
