### ISSUE TITLE
Import Outco email messages to Mench

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2378]
Related to #2350 we can also import Outco's email templates which talk to software engineers looking to get hired as intent messages to better pitch Mench to software engineers who are looking to get hired.

Here are some emails I received from them so far:

## How This Self Taught Dev Landed a Job During Week 5 of Outco

Hey ,

My names Dan and I’m one of the co-founders of Outco.

Outco is Silicon Valley’s best kept secret to help developers land a better, higher paying job than they ever thought possible. 

It sounds hard to believe, but after working with over 1,000 software developers we guarantee  the “black box” of an the interview process can become a predictable, manageable and (relatively) straightforward problem that you can tackle if you're willing to put in the work. 

Speaking of work, Outco is designed to be completed while you have a full-time job. 

We meet Monday through Thursday from 6-9 PM EST/PST with two separate east coast and a west coast cohorts. Our remote course offering allows you to land a job in another state or on the other side of the country no matter where you are. 

That's what happened to one of our Outcoders Stewart.

Stewart had a Degree in Physics, and was going for his Ph D in New Hampshire when he realized academia wasn’t right for him. He was a self-taught developer, but had only ever had one "real programming" job. 

Meanwhile, his partner had to relocate to Los Angeles for work on the other side of the country. 

Enter Outco remote.

Stewart was able to start week 1 in New Hampshire and by the time week 5 came around he had moved to LA AND had an offer all lined up at a great company. 

Here’s Stewart’s experience in his own words:

“Applying to software engineer positions was a little bit like fumbling around in the dark. I felt lost and unsure what I was doing.

Before Outco on the technical side I was brushing up on algorithms and data structures, but I wasn’t really sure if I was on the right track. Outco does a really good job putting your feet to the fire to make sure you practice the skills that you actually need to practice. 

They show you how to answer questions and what interviewers are really looking for. Every engineer has the substance already - it’s about learning how to frame that experience in a way that employers are really attracted to. 

Something that surprised me in the program was how personal they get with every single student. There were many instances where I’d be filling out the worksheets or journals and the very next morning there were 5-6 comments on it. 

That kind of fast turn around and attention to personal details went above and beyond any other educational program I’ve been apart of.”
 

If you’re ready to learn more about Outco or have any questions either reply to this email or show up for the next info session this week.  

And if you’re all set with that, the next step is to apply. 

All the best,

Dan
Outco Co-Founder

## Becoming An Engineer at AirBnB While Doubling His Salary

Hey ,

I’ve been helping engineers land better jobs for almost 3 years now, and each month I’m still amazed by the offers our Outcoders get. 

And I’m not just talking about the “rockstar programmers” although we also help them land better jobs as well.

There's actually a specific methodology we follow and it works for junior and senior engineers just the same. 

Take Adell who landed at AirBnb at double his previous salary (not including stock options). Adell is a former bootcamp graduate (no CS degree) who admits he’s not the strongest at algorithms.  

How did this relatively junior engineer get such an amazing offer from a great company?

That’s what we at **Outco call gathering leverage**.

See Adell was working at a decent company, but was unsure about the future of his job trajectory. Note, if you’re unsure about your current job, then you don’t have much leverage.

To gain leverage, Adell planned to get as many offers as possible, which meant **doing onsite at over 20 companies**. 

Here's how he prepared for these interviews in his own words
 

“Historically I had struggled with data structures and algorithms, I may be a little above average, but I wanted to be amazing at them. 

My strategy was to put the interviews for my ideal target companies at the very end (I moved my onsite at Google back a month) so I interviewed at smaller startups first, then medium-sized companies, and then the big companies like Airbnb and Google at the end. 

A really big component of my improvement in DSA came from teaming up with another student at Outco. To prepare for my onsite with Google scheduled me and the other student would even practice on the weekends.

I didn’t think I’d get that many on-sites, but from my phone screens I did about 20 on-sites and had over 10 offers.

It was interesting, historically I thought I did well on interpersonal skills during interviews, but I got some feedback early in my job search that I was underperforming on my resume deep dive. 

I feel really grateful that I got to hone in on that aspect of my job search with Dan and that I was able to received feedback early on from a recruiter when I underperformed.”
 

At Outco you will receive more feedback on your technical and interpersonal interviews than you will ever receive in your life. 

If you're ready to take the next step in your career, be sure to attend our next info session or apply today. 

All the best,

Dan
Outco Co-Founder

## What to Expect from the Outco Admissions Process

Hey ,

If you’ve been wanting to start a new dev job and take the next step in your career, what are you waiting for?

Each week you delay a new salary increase you could be giving up $500-$2,000 depending on your offer. 

Our average junior engineer signing bonus is $9,666 so that alone will cover the cost of our program. 

If you are feeling like now is the time to make a chance, here's the next steps for the admissions process. 
 

Step 1 - Apply to submit your background and coding experience (15 minutes)

We only accept students into Outco who we know we can help. However, don’t be discouraged from applying. You can apply more than once and if we feel you don’t have enough experience we’ll give you actionable steps on exactly what to do to be a stronger engineering candidate. 
 

Step 2 - Schedule a fundamentals check with one of our team members (30 minutes)

The fundamentals check is with one of our technical coaches and our goal here is to see how well you communicate and respond to feedback. We’ll also be making sure you have “mastered” your programming language of choice. 

If you want to prepare, be ready for string manipulations, traversing arrays, writing and utilizing functions - fairly basic programming skills. 
 

Step 3 - Decide which payment and course plan is right for you

After you are accepted, you get to choose which cohort and payment methodology is right for you. We put our money where our mouth is and offer payment plans that best fit your current cash flow situation. 

You can choose to pay:

- $5,000 paid upfront in full for the 5-week program
- $1,500 up front + 5% of your first year’s salary paid over 3 months after your start date
- $0 upfront in exchange for 10% of your first year’s salary paid over 6 months after your star date

If you have any questions feel free to respond here to me or take the next step and [apply now](https://www.outco.io/apply). 

All the best,

Dan
Outco Co-Founder

## [Video Interview] How Ryan Lands a Job at Microsoft 

Hey ,

I’ll keep this email short because I know you’re busy. 

There’s two quick things I want to make sure you understand about Outco. 

#1 Outco was designed for you to complete while you have a full-time job. That’s why we meet 6-9 EST or PST so you can attend after work hours. 

#2 You will be applying and interviewing at companies during Outco. This isn’t just classroom content, you’ll receive 1-on-1 and small group support throughout your interview and negotiation process. 

For instance, take Ryan, he was flown to Seattle to interview at Microsoft during Week 3 of Outco. 

[Watch this Youtube video interview](https://www.youtube.com/watch?v=PnmOUAZRMk0) with him to learn what topics they covered during the interview and how Outco dealt him 'the royal flush' and helped him land the highest possible marks on each interview. 

Full interview - [https://youtu.be/PnmOUAZRMk0?t=482](https://youtu.be/PnmOUAZRMk0?t=482)

If you’re ready to take the next step in your engineering career be sure to attend [our next info session](https://www.outco.io/info-session-signup) or [apply for our next available cohort](https://www.outco.io/apply). 
 

All the best,

Dan
Outco Co-Founder

**Comment by grumo** [comment]
@shervine great emails. The most effective sales copy comes from success stories. They are doing a great job at leveraging those. We should do the same as soon as we start getting our own success stories from companies, users, and miners.

**Comment by grumo** [comment]
@shervine closing for now as not related to top priority of getting companies to use Mench as a candidate selection tool.

**Comment by shervine** [comment]
Will keep this open for now as a way to grow users once we shift focus on them...

**Comment by shervine** [comment]
Not our focus now as our primary customers are companies
