### ISSUE TITLE
Write mining principle to limit total number of characters delivered at once to users

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2380]
Goal: to ensure best possible user mobile experience and reduce amount of back scrolling after messages are delivered.

Intent principle here: https://mench.com/intents/10898#intentnotes-10898

(Inspired by issue #2368)

**Comment by shervine** [comment]
@grumo This is a good idea, but we should also have a principle to always use the mench platform to register and re-use URLs so we ensure all URLs are tied to an entity... Sent you a voice note on this

**Comment by shervine** [comment]
I will be fixing that bug via Fix URL Bug in Messages #2381

**Comment by grumo** [comment]
@shervine I added new intent mining principle on how to properly add URLs to messages here: https://mench.com/intents/10951
