### ISSUE TITLE
Learn about existing knowledge aggregation terminology, solutions, and history  

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2387]
@shervine I think is very important for us to understand the history, terminology, and current solutions in knowledge aggregation and distribution. I've curated some Wikipedia articles on these topics that I believe we'll help us gain a common understanding and vocabulary. 

https://en.wikipedia.org/wiki/Expert_system
https://en.wikipedia.org/wiki/Knowledge_representation_and_reasoning
https://en.wikipedia.org/wiki/Ontology_(information_science)
https://en.wikipedia.org/wiki/Cyc
https://en.wikipedia.org/wiki/Mindpixel
https://en.wikipedia.org/wiki/Commonsense_knowledge_(artificial_intelligence)
https://en.wikipedia.org/wiki/Open_Mind_Common_Sense
https://en.wikipedia.org/wiki/General_Problem_Solver
https://en.wikipedia.org/wiki/Automated_reasoning
https://en.wikipedia.org/wiki/Ontology_language
https://en.wikipedia.org/wiki/Combinatorial_explosion
https://en.wikipedia.org/wiki/Fuzzy_logic
https://en.wikipedia.org/wiki/Forward_chaining
https://en.wikipedia.org/wiki/Backward_chaining
https://en.wikipedia.org/wiki/Non-monotonic_logic
https://en.wikipedia.org/wiki/Logical_form
https://en.wikipedia.org/wiki/Rule_of_inference
https://en.wikipedia.org/wiki/Explainable_artificial_intelligence
https://en.wikipedia.org/wiki/Abductive_reasoning

**Comment by shervine** [comment]
@grumo Yes great idea, will review them after our MVP launch
