### ISSUE TITLE
Mass Search/Replace Intent Outcomes

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2389]
A new admin tool that enables us to quickly manage mass intents outcomes with a quick find/replace workflow.

**Comment by shervine** [comment]
@grumo Now we have a new and useful tool added to Admin tools:

*Intent Search/Replace Outcomes*:

https://mench.com/admin/tools/in_replace_outcomes

You can search for any string in all intent outcomes, and then define a replacing string to quickly modify mass intents no matter where they are. This for example helps me do #2349 in a few seconds. . We still need more mass tools so we can be able to search entity outcomes and intent notes which will be released via #2343

**Comment by grumo** [comment]
@shervine this is awesome!
