### ISSUE TITLE
AND Intent Regular Expression Match V1

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2394]
@shervine on assessments it would be very useful to have a AND text submission type where Mench checks the submission against an answer. The miner would choose "Text match" from the dropdown and enter the string/s that represent the correct answer.

**Comment by shervine** [comment]
@grumo I really like this idea as I had been thinking of allowing regular expression matches to validate a user input in a very flexible way. If they fail to get it right, we can always give 0 completion marks. If they get it right, the miner can define the completion marks.
