### ISSUE TITLE
Analyze Triplebyte on-boarding flow for companies

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2395]
Companies can instantly sign up for a free triplebyte account. This is the information shared during onboarding:

## How Triplebyte works

1. **We interview candidates**: We source candidates and put them through 2-hour interviews with senior engineers. 3% pass. We match them to your roles.
2. **You judge culture fit**: You conduct a 30-minute "Pitch call" with candidates you're interested in to screen them for culture fit and pitch your company.
3. **Engineers go straight to onsite**: We've technically pre-screened candidates, so you take them straight to your final onsite interview. We coordinate travel for out-of-town candidates.
4. **You make hires**: 40% of onsites through Triplebyte result in an offer.
This is twice the industry average.

## Who we work with

1. **Our candidates have a broad range of engineering backgrounds**: We work with back-end, front-end, full-stack and mobile engineers, as well as distributed systems and data pipeline specialists, and generalists of all kinds.
2. **We place candidates in four major tech hubs and remote positions**:
   - New York
   - Seattle
   - San Francisco Bay Area
   - Los Angeles

NOTE: Our screening does not currently cover machine learning or devops. We also do not place engineers outside of our four regions unless they are remote candidates.

## Triplebyte candidates

1. **Triplebyte extensively screens candidates**: Only 3% pass: Engineers go through an adaptive test and a 2-hour technical interview with a senior engineer. Only 3% of candidates are accepted. Learn more by reading "Triplebyte screening process" section below...
2. **As a result, Triplebyte engineers are better**: 40% onsite to offer rate: Triplebyte engineers receive job offers after 40% of onsite interviews. This is twice the industry standard rate.

## Terms of Using TripleByte

**To access our pre-screened candidates, we need you to commit to not do any additional technical screening before your onsite.**

- Companies' trust in our technical evaluation creates an expedited interview process for candidates. This allows us to attract top engineers for you to hire.
- You'll still have the opportunity to select who you reach out to, to screen for culture fit, and to run your full onsite interview process.

## Triplebyte Pricing

- Only pay for the hires you make
   - We charge 20% of the candidate’s starting base salary when you make a hire. 
   - You pay only 10% if the candidate has less than 1 year of experience.
   - We offer a full refund if a candidate leaves for any reason within 6 months.
- Let us worry about travel
   - Triplebyte coordinates and pays for all flights and hotels for candidates. 
   - We charge you a flat $500 fee for each out-of-town candidate you bring on site.

-----------------------------------------

## Triplebyte screening process

The Triplebyte technical screen is completely background blind and has 2 steps. First, candidates complete a screening quiz. Second, candidates interview for 2 hours with a senior engineer. The content of the quiz and interview vary (we run several different versions of each). About 3% of candidates who apply pass both the quiz and interview and are introduced to companies.

### Quiz

Our quiz is an adaptive, multiple-choice test. We've assembled a large pool of potential questions, and the quiz asks each candidate different questions, based on where they have shown strength and weakness. By doing this we are able to get more accurate results in a shorter amount of time. The statistical model we use for our quiz (item response theory) is similar to what is behind the GRE and GMAT tests. Most of the quiz questions involve looking at blocks of code and answering questions about them (finding bugs and predicting behavior). Some questions test specific knowledge.

NOTE: 10% of candidates pass the quiz

### Technical Interview

Our interview is 2 hours long, and is conducted over screen share. We watch candidates work in their strongest language in their own environment. Our interviewers are all experienced engineers (the team includes past employees of Google, Facebook, Dropbox, Uber and Apple). We change the content of the interview over time (as we test new content). However, most interviews contain the following sections:

1. Coding section: Here we give the candidate a spec, and ask them to write a program solving a problem. We look at their process, problem solving and ability to convert idea into code.
2. Debug section: Here we gave the candidate a large existing program, and ask them to find and fix bugs. This better measures the abilities of experienced engineers to work with a large code base.
3. Deep dive: The exact content depends on the interview. But we ask a series of questions about CS fundamentals, back-end web, front-end web, mobile and low-level systems. The questions get harder as we go. Our aim is to measure how deep each candidate can go.
4. System design: Here we give the candidate a spec for a large system (that would take weeks to complete), and have them talk about big-picture architectural concerns. We look for good discussion of tradeoffs.

For top performers on our quiz, we offer an expedited interview to move them through our process faster. These candidates succeed in onsites at a high rate, and the expedited process increases companies' probability of convincing them to join. The expedited interview covers the same topics as our regular interview, but each in a shorter time frame.

About 30% of candidates who do our interview pass and are introduced to companies. The quiz pass rate (10%) times the interview pass rate (30%) gives a total pass rate of 3%.

NOTE: 3% of candidates pass the quiz and the interview

**Comment by grumo** [comment]
@shervine this is great! I noticed they continuously emphasize the fact that only 3% pass their filtering process. I think our ability to create very personalized tests for specific jobs at specific companies could help us/them identify that top 3% with less manual effort.

**Comment by shervine** [comment]
@grumo Yes, we need to discuss this during our meeting tomorrow as it related to our pricing for Partner Employers...

**Comment by shervine** [comment]
@grumo Attached is the TripleByte company agreement.

[Triplebyte Agreement 2019 - Lazymeal.pdf](https://github.com/askmench/mench-web-app/files/3255166/Triplebyte.Agreement.2019.-.Lazymeal.pdf)
