### ISSUE TITLE
Merge Audio/Video/Image/File into Media Response

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2413]
Instead of having all of these as separate AND types, we can merge them into a single "Media Response" AND which would support any of the above. The intent messages can specify to the user what exactly is needed like "video of yourself under 1 minute" or "PDF resume" or "voice note explaining your thoughts"

@grumo Thoughts?

**Comment by grumo** [comment]
@shervine this simplifies it but if the miner asks for a video and the user submits an audio file, text, file, etc. the system would still consider it a proper submission. Maybe we would need an additional AND type called the AND-Any which would allow for any kind of submission.

**Comment by shervine** [comment]
Not a priority at this time
