### ISSUE TITLE
Schedule demo with Allyo conversational recruitment platform

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2414]
They just [raised $45million ](https://venturebeat.com/2019/06/05/allyo-raises-45-million-for-its-ai-driven-hiring-and-onboarding-platform/)to do something similar than us: https://www.allyo.com/

AllyO is an AI technology company with a simple mission – make recruiting delightful and efficient for everyone. It addresses the traditional inefficiencies of lost applicants and conversions due to poor candidate experience, the high cost of recruiting due to overburdening of administrative tasks on hiring teams and lack of visibility and control for HR leadership. It utilizes deeply conversational AI to fully automate an end-to-end recruiting workflow by intelligently engaging via texting over mobile and web. It is used by Fortune 500 enterprises that have experienced a 2-6X increase in applicant capture and conversion rate, 91 percent application completion rate and over 50 percent reduction in cost and time to hire.

AllyO is backed by leading investors such as Gradient Ventures (Google’s AI fund), Randstad Innovation Fund, Sapphire Ventures, Bain Capital Ventures, Cervin Ventures and Scale Venture Partners. AllyO is headquartered in Mountain View, California. For additional information, please visit us at allyo.com, LinkedIn or Twitter.

**Comment by shervine** [comment]
@grumo great research. Looking forward to experiencing their product and learning from their approach.
