### ISSUE TITLE
Approach 100 companies hiring developers and pitch Mench

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2419]
Steps:
- [x] Find 100 job openings: (i.e: [Full stack jobs in Vancouver](https://www.google.com/search?q=full+stack+developer+jobs+vancouver&oq=full+stack+developer+jobs+vancouver&aqs=chrome..69i57j0l5.8039j0j4&sourceid=chrome&ie=UTF-8&ibp=htl;jobs&sa=X&ved=2ahUKEwiF2ID6sdniAhXFTRUIHalHCN0Qp4wCMAB6BAgKEAE#htidocid=tiKnrFpDmXUBidUzAAAAAA%3D%3D))
  - [x] Spreadsheet with 200+ companies hiring programmers in Vancouver
- [ ] Convert each job to a Mench intent (i.e.: https://mench.com/10707)
  - @shervine create an automatic job parser as per #2415
- [ ] Find each company HR manager on LinkedIn
- [ ] Send [pitch email](https://docs.google.com/document/d/11xW9FHFtlUMkSr-DQkLbo9Cftx8JaZZOh4Mnb-6Sl94/edit#) via LinkedIn (max 300 characters)
- [ ] Measure conversions

Target HR managers reviewing HR software: https://www.capterra.com/p/110968/BambooHR/

**Comment by shervine** [comment]
@grumo Yes this is awesome, will keep you posted on my progress too

**Comment by grumo** [comment]
@shervine Let's use https://linkedhelper.com/ to contact LinkedIn HR managers [automatically](https://medium.com/linked-helper/collect-select-invite-2nd-3rd-linkedin-connections-4f9d41628467?mbf638=1561603686488) (Set limit to 100 mgs/day):

Let's break our outreach efforts by city:

- [ ] [Vancouver](https://www.linkedin.com/search/results/people/?facetGeoRegion=%5B%22ca%3A4880%22%5D&keywords=HR%20Manager&origin=FACETED_SEARCH)
- [ ] San Francisco

**Comment by grumo** [comment]
@shervine we can collect emails in [this spreadsheet](https://docs.google.com/spreadsheets/d/1YC7NQULtc7tsQuRiEezZ7ylqAp3fhn00xrSKtI6fAI4/edit#gid=0)

**Comment by grumo** [comment]
@shervine Craiglist has very few jobs and most require to apply via the company website. I'm going ask our contact in Upwork to get an estimate to get HR manager's emails.

**Comment by grumo** [comment]
@shervine our Upwork contact could get us HR manager emails (tracking job postings) at $0.5 per email.

**Comment by shervine** [comment]
@grumo Given our conversation today, I think its best to aim to setup an automated top-funnel where we scrape companies with active software engineering job postings and try to get the "person responsible for hiring software engineers"

The issue with this strategy is that each batch of leads would cost us money so it would not be sustainable until we have a steady stream of revenues.
