### ISSUE TITLE
Position Mench as ATS alternative for Companies

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2425]
Application Tracking systems set the current standards for companies to auto-sort their candidates, and based on our recent discussions, we're moving in this market to offer companies an easy way to accurately sort through their applicants and then advance them through their recruitment funnel. More information on ATS systems [here](https://www.jobscan.co/blog/8-things-you-need-to-know-about-applicant-tracking-systems/). Also the current [market size for ATS is $1.2B](https://www.businesswire.com/news/home/20180709005747/en/Global-1.81-Billion-Applicant-Tracking-System-Market) which seems like a super-focused/niche/good-sized market for us to approach at this stage.

Mench wants to offer a better solution to companies that instead of an automated keyword-finder bot to scan resumes, Mench would have a personalized conversation with each candidate to better understand their desires, qualifications, and compatibility to each unique job posting.

This is more of a product positioning pivot than anything technical, but I think its important to think of our specific market and ways we can offer substantially more value to both companies AND candidates within this industry...

@grumo Thoughts?

**Comment by shervine** [comment]
@grumo I think it would be a good idea if you can research the revenue model for ATS companies so we can get inspiration for our own revenue model

**Comment by grumo** [comment]
@shervine great idea. I'm looking into Capterra reviews for [ATS software](https://www.capterra.com/applicant-tracking-software/). 
Take aways so far:
- It seems most solutions [charge monthly recurring fees](https://www.capterra.com/applicant-tracking-software/compare/110968-177364-165636-125768/BambooHR-vs-Recooty-vs-Recruiterflow-vs-Zoho-Recruit). i.e: SAAS
- Most offer ATS as one of the many features for candidate management

**Comment by grumo** [comment]
@shervine I recommend you read through customer reviews. It will give us an insight into what customers like/dislike and help us uncover opportunities for improvement/differentiation.
Ie: [Reviews for BreezyHR](https://www.capterra.com/p/141702/Breezy-HR/)

**Comment by shervine** [comment]
@grumo I reviewed the list of ATS platforms and their features and I must say that the SAAS world is quite different than the marketplace world! Since SAAS does not offer any leads, they must offer tons of features to satisfy companies. On the other hand, companies like TripleByte that are marketplaces do not offer extensive features since their core value is in the lead that they will offer, allowing them to keep their features to a minimum just so they can effectively deliver their lead to the company.

Given that we're a marketplace, we want to offer only the core features necessary to manage their Mench candidate funnel, and then focus on offering more value to users/candidates so we can attract more of them which would, in turn, attract more companies as the primary value of a marketplace is in the leads its offers.

I am still not sure about the best pricing model as we're trying to do a hybrid model here... SAAS usually charges a fixed fee and does not access/share your data. Marketplaces usually charge a percentage of the annual salary and own the entire data.

**Comment by grumo** [comment]
@shervine it seems the best strategy to build the marketplace is to get companies to send us their leads and pay us to use Mench to filter the best candidates. It's hard to beat getting paid to get leads!
In terms of pricing model, we can either charge per job posting or a recurring fee to allow them to post an X number of postings per month. Once we have built the user side, we could also start getting paid for candidate referrals like TripleByte or any traditional recruitment company does.
For now, I suggest we stick to finding one company with one job posting to test our product. The sooner we have a success story, the easier we'll be to onboard more companies and get more leads.

**Comment by shervine** [comment]
@grumo On the same page. Will continue building our company MVP so we can get our first partner company ASAP.
