### ISSUE TITLE
Integrate with Candidate Management APIs

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2443]
@shervine I predict many target companies will have existing candidate management tools in place. It will be a lot easier to bring them onboard if we can integrate with their existing tools.
The integration would send an API call to the existing tool to create a new candidate ONLY when the candidate meets the requirements set in the Mench job application.

Zapier would be a simple way to do so but we'd need to be listed in their marketplace which will only happen once we have enough traction/klout.

For now, I suggest we create API integrations with the top 3 players and add more as we get more companies onboard.

Here is the list of top candidate management tools: https://www.capterra.com/applicant-tracking-software/?utf8=%E2%9C%93&feature%5B0%5D=32153&sort_options=Most+Reviews

Here are the API docs for the top 8 companies:
- [ ] https://www.bamboohr.com/api/documentation/
- [ ] https://developer.breezy.hr/
- [ ] https://www.zoho.com/recruit/api-new/
- [ ] https://developer.icims.com/REST-API
- [ ] https://developers.workable.com/
- [ ] https://community.workday.com/sites/default/files/file-hosting/productionapi/Recruiting/v32.1/Recruiting.html
- [ ] https://docs.catsone.com/api/v3/
- [ ] https://api.recruitee.com/docs/index.html

**Comment by shervine** [comment]
@grumo Great idea! Will incorporate this into the roadmap for our company MVP product

**Comment by shervine** [comment]
@grumo I mined these companies into Mench as I would need to have them as entities to build-out the recruiter API infrastructure.

https://mench.com/entities/7326

**Comment by shervine** [comment]
@grumo We will not do this for now, and only do so if our paying company clients are asking for it, and then we would do it with whatever ATS they have
