### ISSUE TITLE
Evaluate Pairin Hiring/Assessment Software

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2444]
Just had a call with their team to get an intro of their software.

- Only soft skill assessments (no technical assessments)
- Based on simple adjectives that takes 7-10 minutes to complete by user
- Very complex UI with graphs and charts

We got demo access for 14 days to test:

---------------------------------------

Hi Shervin,

Thank you again for joining me on the demo today. To follow up to our call I have included additional information regarding our tool for hiring. I’ve also included some helpful links below to our Science FAQ, a video overview of the hiring tool, and login information for your new trial account.  

PAIRIN hiring video – https://youtu.be/ROe25BA2E8Q
PAIRIN science FAQ - https://pairin.com/our-science-faq/

Log into your trial account with your email address, temporary password - Pairin19
Login at https://app.pairin.com/

Regards,

Travis Desmond
Sales Manager
tdesmond@pairin.com
303-406-3453
www.pairin.com

**Comment by shervine** [comment]
Elements they screen for designed based on the Adjective Check List ([Wikipedia](https://en.wikipedia.org/wiki/Adjective_Check_List)). The READINESS target consists of 20 abilities, mindsets and behavioral patterns that most lead to success in our rapidly changing workplace. These skils were identified by a broad range of employers and educators. Ranges are general and will shift or narrow based on one occupation versus another.

## 300 Adjectives

1. **Enthusiastic**: Eager; full of interest and motivation.
2. **Hard-Headed**: Firmly reasoned; hard to persuade otherwise.
3. **Mainstream**: Based on what is acceptable by most people.
4. **Opinionated**: Expressive of very strong or stubborn beliefs and judgments.
5. **Airheaded**: Lost in thought; distracted or inattentive.
6. **Unstable**: Unsteady; emotionally unbalanced or irrational.
7. **Disoriented**: Confused as to my direction or identity.
8. **Stingy**: Reluctant to give or spend.
9. **Complaining**: Expressive of unhappiness or discomfort; fault-finding.
10. **Sophisticated**: Experienced in culture, fashion, literature or other worldly ways.
11. **Alluring**: Powerfully and mysteriously attractive.
12. **Confused**: Unable to understand or think clearly.
13. **Cheerful**: Noticeably happy and good-spirited.
14. **Talkative**: Chatty; eager to join in conversation.
15. **Limited Interests**: Concerned or involved with a few subjects or activities.
16. **Attractive**: Pleasing and appealing to the senses or mind.
17. **Preoccupied**: Absorbed in thought; obsessed; caught up with something.
18. **Conceited**: Unjustifiably prideful of my actions and abilities.
19. **Bitter**: Angry or unhappy due to bad experiences or unfair treatment.
20. **Loyal**: Faithful and devoted to someone or something.
21. **Reserved**: Slow or unwilling to share emotions or opinions.
22. **Timid**: Easily frightened; lacking courage or confidence.
23. **Forgiving**: Inclined to pardon and let go of resentment.
24. **Immature**: Childish or silly.
25. **Outspoken**: Freely, openly or boldy speaking your mind; direct.
26. **Worrying**: Troubling, bothersome, distressing.
27. **Organized**: Methodical, orderly and efficient.
28. **Peaceful**: Harmonious; inclined to avoid argument or conflict.
29. **Reflective**: Deeply or seriously thoughtful; contemplative.
30. **Unrealistic**: Impractical, idealistic or naïve.
31. **Weak**: Lacking ability or stability; without power to cope.
32. **Dreamy**: Absorbed in faraway thought or imagination; preoccupied.
33. **Forgetful**: Unable to remember well; inattentive.
34. **Humble**: Not wanting to be noticed or given special treatment.
35. **Formal**: In line with fixed customs, rules and requirements.
36. **Defensive**: Protective against the real or imagined threat of criticism.
37. **Irritable**: Easily annoyed or angered.
38. **Anxious**: Uneasy or worried, especially about what may happen.
39. **Cautious**: Careful to avoid risk or danger.
40. **Withdrawn**: Very shy, reserved or introverted.
41. **Selfish**: Concerned mostly or only with myself.
42. **Robust**: Strong and bold.
43. **Self-Denying**: Willing to sacrifice my own wants or needs.
44. **Sarcastic**: Snarky or mocking; using sharp or unkind words and tones.
45. **Curious**: Eager to investigate, learn or know; inquisitive.
46. **Self-Centered**: Concerned solely with my own desires, needs or interests.
47. **Stable**: Calm, reasonable and not easily moved.
48. **Responsible**: Reliable; able to make good decisions and do what is expected.
49. **Persistent**: Firmly or stubbornly continuing, despite difficulty or disapproval.
50. **Inventive**: Able to think of new ideas and methods.
51. **Affectionate**: Warm, loving and tender.
52. **Ingenious**: Highly clever, inventive and resourceful; brilliant.
53. **Rigid**: Unwilling to change or adapt to situations.
54. **Rude**: Without respect for or consideration of others; impolite.
55. **Gentle**: Tender and calm; kind or mild.
56. **Insightful**: Exhibitive of clear and deep understanding.
57. **Unconventional**: Different from what is usual or widely accepted.
58. **Warm**: Friendly and affectionate.
59. **Tactful**: Sensitive in dealing with others or with delicate issues.
60. **Honest**: Truthful, sincere; free from cheating or stealing.
61. **Broad Interests**: Concerned or involved with many subjects and activities.
62. **Realistic**: Able to see things as they are and deal with them sensibly.
63. **Contented**: Happy; satisfied with things as they are.
64. **Deeply moved**: Emotionally touched or affected.
65. **Alert**: Mentally aware and attentive.
66. **Thrifty**: Careful with money; economical.
67. **Dishonest**: Willing to do things that are deceptive, unfair or corrupt.
68. **Hostile**: Very unfriendly.
69. **Ambitious**: Eager for success or achievement.
70. **Good-Looking**: Pleasing or nice in appearance.
71. **Unselfish**: Kind and giving.
72. **Intentional**: Unhurried; carefully assessed and considered.
73. **Rational**: Guided by reason or sound judgment; sensible.
74. **Wise**: Able to use knowledge; discerning what is true, right or lasting.
75. **Simple**: Not showy; plain or natural.
76. **Distractible**: Easily disturbed or diverted from focusing attention.
77. **Efficient**: Able to achieve maximum output with minimum resources.
78. **Rebellious**: Resistant to or defiant of authority or tradition.
79. **Dependent**: Reliant upon someone or something else.
80. **Understanding**: Perceptive, discerning and empathetic.
81. **Quarrelsome**: Disagreeable; tending to argue.
82. **Unpredictable**: Changing suddenly, without reason or warning; undependable.
83. **Dominant**: Dictating, ruling over others.
84. **Uninhibited**: Free and spontaneous; unselfconscious.
85. **Prudish**: Very concerned with proper conduct, speech or dress; strict.
86. **Wary**: Cautious and suspicious.
87. **Resourceful**: Clever and efficient in using what's available, especially in difficult situations.
88. **Relaxed**: Free from stress, worry or tension; informal.
89. **Generous**: Ready to give freely and more than is expected.
90. **Spontaneous**: Without planning or thought; spur-of-the-moment.
91. **Excitable**: High-strung; easily stirred emotionally.
92. **Nagging**: Annoying, scolding or urging others; complaining.
93. **Foolish**: Unwise; lacking good sense or judgment.
94. **Complicated**: Hard to analyze, understand or explain.
95. **Straightforward**: Very direct and honest in expression; outspoken
96. **Calm**: Peaceful, chilled out, free from agitation.
97. **Self-Seeking**: Interested in myself; advancing my own desires and goals.
98. **Clear-Thinking**: Free from confusion.
99. **Matter-of-fact**: Expressive of little or no emotion or interest.
100. **Fault-Finding**: Very critical; hard to please.
101. **Bullying**: Noisily pushy; often full of empty threats.
102. **Assertive**: Boldly self-assured, confident without being overbearing.
103. **Superstitious**: Believing in the power of magic, chance or luck.
104. **Energetic**: Full of life and stamina.
105. **Emotional**: Easily affected with or expressive of feelings.
106. **Methodical**: Orderly and systematic; careful about detail.
107. **Headstrong**: Stubborn; unwilling to do what others want.
108. **Natural**: Relaxed, real, open and uninhibited.
109. **Pessimistic**: Prone to expect or see the worst; gloomy.
110. **Deceitful**: Tricky, misleading or cheating.
111. **Mild**: Moderate, pleasant or gentle.
112. **Flirtatious**: Suggestive of affection in a playful way.
113. **Soft-Hearted**: Tender and compassionate.
114. **Bossy**: Pushy; fond of telling people what to do.
115. **Dignified**: Composed or serious; worthy of respect.
116. **Humorous**: Funny, witty, comical.
117. **Self-Confident**: Firmly trusting and secure in my abilities.
118. **Considerate**: Concerned for the rights, feelings and needs of others; kind.
119. **Sincere**: Up-front, honest and trusting.
120. **Spineless**: Lacking courage or willpower.
121. **Spunky**: Lively, brave and determined.
122. **Optimistic**: Positive and hopeful that the best possible thing will happen.
123. **Clever**: Mentally quick and resourceful.
124. **Changeable**: Readily moving or shifting; not fixed.
125. **Careless**: Lacking in attention to what matters.
126. **Aggressive**: Boldly assertive and prone to competitiveness
127. **Tender**: Gentle, sympathetic and nurturing.
128. **Show-Off**: Flashy; trying to attract attention or impress others.
129. **Unfriendly**: Distant or unsociable.
130. **Controlling**: Quick to command or rule over others
131. **Cowardly**: Lacking courage; fearfully timid.
132. **Dependable**: Trustworthy and reliable.
133. **Self-Controlled**: Able to keep my thoughts, emotions and actions in check; self-regulated.
134. **Progressive**: Motivated to bring improvements and reforms to society or individuals.
135. **Original**: Different and unique; able to generate new ideas or things.
136. **Polished**: Very skillful or impressive; elegant.
137. **Pleasure-Seeking**: Eager for happiness, enjoyment or satisfaction.
138. **Kind**: Thoughtful; helpful to others.
139. **Prejudiced**: Biased; unfair in judging someone or something.
140. **Vindictive**: Eager to punish or "pay back" rather than forgive.
141. **Initiative**: Ready and able to make things happen.
142. **Cruel**: Willfully causing pain, suffering or distress.
143. **Silent**: Quiet, not saying much.
144. **Easy Going**: Relaxed, laid back and informal.
145. **Wholesome**: Decent, morally good, strong valued.
146. **Meticulous**: Carefully attentive to details and hard-working.
147. **Hard-Hearted**: Unfeeling; unmoved by pity or warmth.
148. **Sympathetic**: Feeling compassion, sorrow, or pity for the distress of others.
149. **Severe**: Strict and stern; harsh.
150. **Fearful**: Scared or afraid.
151. **Confident**: Assured; not doubtful.
152. **Logical**: Capable of clear or valid reasoning.
153. **Disorderly**: Messy, untidy; disruptive or out of line.
154. **Strong**: Powerful, forceful or vigorous.
155. **Tight-lipped**: Good at keeping secrets.
156. **Quiet**: Calm or reserved; low-key.
157. **Helpful**: Willing to assist.
158. **Trusting**: Inclined to believe that others are good and honest.
159. **Visionary**: Thinking ahead; able to imagine what might happen.
160. **Hurried**: Quick or rushed.
161. **Well-planned**: Intentional; serious about advanced preparation.
162. **Unassertive**: Quiet and shy.
163. **Self-Pitying**: Feeling sorry or sad for myself.
164. **Dissatisfied**: Discontented, unhappy.
165. **Inconsiderate**: Insensitivity; lack of consideration in dealing with others.
166. **Reckless**: Carelessly unconcerned about consequences.
167. **Irresponsible**: Unreliable; careless about consequences.
168. **Wacky**: Wildly funny, eccentric; wacky.
169. **Submissive**: Willing to do what others want.
170. **Hard-working**: doing tasks carefully and with much effort.
171. **Sociable**: Eager to be with other people; outgoing.
172. **Shy**: Uneasy about talking with people or being the center of attention.
173. **Emotionless**: Objective; not showing feelings.
174. **Steady**: Consistent and dependable.
175. **Witty**: Funny and clever.
176. **Tough**: Strong and able to deal with difficult situations or pain.
177. **Mischievous**: Playfully annoying or unruly.
178. **Smug**: Overly self-satisfied and content.
179. **Determined**: Firmly decided in purpose or intent; resolved.
180. **Obnoxious**: Very annoying and unpleasant.
181. **Sentimental**: Easily affected by emotions such as love, sadness, pity or nostalgia.
182. **Pleasant**: Agreeable and likeable.
183. **Unexcitable**: Calm or unemotional.
184. **Stern**: Strict, demanding, authoritarian.
185. **Distrustful**: Disbelieving; suspicious or doubtful about others.
186. **Restless**: Unable to relax or settle; bored or longing for change.
187. **Erratic**: Given to unpredictable moods or behaviors.
188. **Unaffected**: Not easily influenced or emotionally moved.
189. **Bragging**: Inclined to overstate or exaggerate.
190. **Disinterested**: Uncaring, unfeeling.
191. **Poised**: Calm, composed and self-assured.
192. **Impressionable**: Easily influenced by other people.
193. **Dull**: Uninteresting; without liveliness.
194. **Reasonable**: Sensible and fair.
195. **Adventurous**: Willing to undertake new and daring things.
196. **Intelligent**: Able to learn and understand things.
197. **Rugged**: Tough, strong, and sturdy.
198. **Leisurely**: Doing things as convenient or when ready; deliberate.
199. **Good-Natured**: Friendly, easygoing and respectful.
200. **Arrogant**: Displaying an offensive sense of superiority or self-importance.
201. **Greedy**: Excessively eager to acquire more of something.
202. **Handsome**: Impressive or good-looking.
203. **Thankless**: Unappreciative or ungrateful.
204. **Passive**: Lacking enthusiasm or interest.
205. **Cynical**: Distrusting the sincerity of all human motives—except selfishness.
206. **Sharp-Witted**: Quick to notice and understand things.
207. **Careful**: Thoughtful; guided by a sense of what is right or true.
208. **Childish**: Lacking maturity; babyish.
209. **Conservative**: Likely to resist change or innovation.
210. **Sensible**: Practical; based on actual or usual actions rather than theory.
211. **Impatient**: Unable or unwilling to wait.
212. **Sensitive**: Responsive to the feelings, moods or reactions of others.
213. **Loud**: High in volume or intensity; noisy.
214. **Individualistic**: Independent or different from others; unique in personality.
215. **Capable**: Able to do or accomplish things well.
216. **Sluggish**: Lacking ambition or purpose; idle.
217. **Moody**: Given to sharp emotional shifts; often gloomy or grumpy.
218. **Undependable**: Unreliable; unable to be trusted.
219. **Sly**: Sneaky, tricky, mischievous.
220. **Polite**: well-behaved and courteous.
221. **Meek**: Gentle; self-restrained from aggression or resentment.
222. **Perceptive**: Good at judging what people or situations are reallylike.
223. **Reliable**: Able to be trusted to do what is needed.
224. **Whiny**: Complaining; cranky.
225. **Thorough**: Careful not to miss or omit any detail.
226. **Hasty**: Speedy; with little thought.
227. **Independent**: Self-directed; free from external control or constraint.
228. **Persevering**: Persistent in worthwhileactivities, despite challenges or setbacks.
229. **Nervous**: Fearful, timid, anxious or apprehensive.
230. **Unambitious**: Having little desire for success or achievement.
231. **Discouraged**: Very sad and without hope.
232. **Noisy**: Unpleasantly loud.
233. **Praising**: Likely to express approval; complimentary.
234. **Adaptable**: Capable of adjusting to fit different situations.
235. **High-Strung**: Tense; easily upset.
236. **Modest**: Not too proud or confident, humble; reserved.
237. **Active**: Lively and involved; energetic about doing.
238. **Egotistical**: Conceited; self-centered in expression.
239. **Excessive**: Carelessly wasteful with money.
240. **Crabby**: Grouchy, cranky or irritable.
241. **Laid-Back**: Calm and composed; not affected by strong feelings.
242. **Imaginative**: Likely to think in lively ways; clever with mental pictures or concepts.
243. **Balanced**: Well-adjusted; in good condition.
244. **Moderate**: Not extreme or excessive.
245. **Civilized**: Polite, reasonable and respectful.
246. **Artistic**: Deeply valuing, or making, products of human creativity.
247. **Flexible**: Capable of doing many things.
248. **Suspicious**: Distrustful; likely to have doubts.
249. **Intolerant**: Unwilling to accept the beliefs or behaviors of others.
250. **Patient**: Able to wait or endure calmly; accepting and understanding of other people.
251. **Quick**: Swift in thought or action.
252. **Snobbish**: Snooty, arrogant or stuck-up.
253. **Standoffish**: Emotionally distant, remote or unsociable.
254. **Precise**: Sharply exact, accurate or specific.
255. **Stubborn**: Unwilling to change or stop; firmly resisting.
256. **Daring**: Ready to take risks.
257. **Sloppy**: Careless and messy.
258. **Idealistic**: Determined to see things in perfect but unrealistic ways.
259. **Opportunistic**: Eager to gain an advantage or benefit, regardless of what's right.
260. **Touchy**: Easily hurt or upset; sensitive to criticism.
261. **Gloomy**: Sad or depressed.
262. **Courageous**: Able to overcome fear and persist against danger and difficulty.
263. **Outgoing**: Comfortable meeting and talking to others, friendly.
264. **Shallow**: Unconcerned with complex, heavy or emotionally deep things.
265. **Cooperative**: Eager to work with others toward a common end.
266. **Silly**: Not serious; lacking common sense.
267. **Unintelligent**: Unable to learn or understand things.
268. **Tense**: Stressed-out; nervous.
269. **Compliant**: Ready to do favors for others; accommodating.
270. **Slow**: Taking or requiring a long time; not quickly moved.
271. **Self-Punishing**: Rough, harsh or tough on myself.
272. **Repressed**: Self-conscious; unable to share thoughts, feelings or ideas.
273. **Casual**: Relaxed, friendly and informal.
274. **Neglectful**: Not thoughtful or helpful to others.
275. **Mature**: Adult-like; grown-up.
276. **Jolly**: Happy and cheerful.
277. **Common**: Ordinary; average.
278. **Awkward**: Lacking in grace or skill; clumsy; uneasy or embarrassed.
279. **Quitting**: Likely to give up, drop out or discontinue.
280. **Thoughtful**: Considerate of the feelings or well-being of others.
281. **Peculiar**: Unusual, strange or odd.
282. **Forceful**: Strong and assertive; persuasive.
283. **Fussy**: Picky; concerned with attention to details.
284. **Lazy**: Uneager or unwilling to work or make an effort.
285. **Tricky**: Misleading; able to avoid commitment.
286. **Charming**: Delightful or fascinating, especially in manner.
287. **Argumentative**: Oppositional; set to verbally disagree with others.
288. **Scatterbrained**: Lacking sense or discretion; airheaded.
289. **Friendly**: Kind, caring and pleasant.
290. **Cold**: Unfriendly; without affection or compassion.
291. **Resentful**: Bitter; very angry and upset about unfair treatment.
292. **Harsh**: Rude or offensive.
293. **Serious**: Thoughtful and sincere; not joking or pretending.
294. **Demanding**: Hard to satisfy; insistent.
295. **Tolerant**: Willing to accept the beliefs or behaviors of others.
296. **Delicate**: Sensitive in feeling, understanding, or responding.
297. **Impulsive**: Driven by sudden desires, without thought or prior planning.
298. **Appreciative**: Expressive of gratitude or recognition.
299. **Enterprising**: Proactive; ready to do new and difficult things.
300. **Fair-Minded**: Free from deception, bias or prejudice.

## Mapped to 20 Scales

Accountability
Civic Literacy & Citizenship
Collaboration & Teamwork
Creativity & Imagination
Critical Thinking
Curiosity & Inquisitiveness
Entrepreneurialism
Flexibility & Adaptability
Grit
Initiative
Interpersonal Skills
Leadership
Optimism
Problem Solving
Productivity
Self-Awareness
Self-Control
Self-Regard & Balance
Social Awareness
Social Responsibility & Action

**Comment by shervine** [comment]
@grumo I also sent you an invite to take the assessment so we can consider mining this into Mench if we believe it would add value.

**Comment by grumo** [comment]
Done
