### ISSUE TITLE
Consider hiding forshadowing messages and adding an "info" ⓘ button instead

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2467]
@shervine I feel some of the forshawdowing messages still don't feel right - specially the ones that originally were hidden becase of the :: double colon as is the case for all our assessments.

I propose this solution:

- [ ] ONLY Forshadow next steps IF ALL of them are normal - ie: none of them have :: double colons
- [ ] HIDE next steps if ONE or MORE steps have :: double colons. Instead, add an "info" ⓘ button to the right of the "next" button. The "info" ⓘ Button would trigger the forshadowing and optionally provide some context regarding progress to the user.

**Comment by shervine** [comment]
Merge into Foreshadow AND Intents IF First 5 have non-double-colon Outcomes #2469
