### ISSUE TITLE
Iterate LinkedIn reach out message to HR managers

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2472]
LONGNAME, we'd like to convert one of your job postings into an interactive job application over Messenger. Here's a sample Airbnb job: https://mench.com/10430. Instead of having to go through hundreds of resumes, Mench automatically tells you which are the top 10% candidates. 

LONGNAME, I'm Miguel from Mench.com. Would it ok to add one of your job postings to our recruitment chatbot? Instead of having to go through hundreds of resumes, Mench automatically tells you which are the top 10% candidates. Here's a sample Airbnb job: https://mench.com/10430 

LONGNAME, Would it be ok to add one of your job postings to our recruitment chatbot? Instead of having to go through hundreds of resumes, automatically tells you which are the top 10% candidates. Here's a sample Airbnb job: https://mench.com/10430 

LONGNAME, please let me know if I can add one of your job postings to our recruitment chatbot? Instead of having to go through hundreds of resumes, automatically tells you which are the top 10% candidates. Here's a sample Airbnb job: https://mench.com/10430 

LONGNAME, please let me know if I can add one of your job postings to our recruitment chatbot at Mench. It can save you from having to go through hundreds of resumes and automatically identify the top 10% candidates. Here's a sample Airbnb job: https://mench.com/10430 - We just launched so there is no cost.

LONGNAME, Could we add one of your job postings to our recruitment chatbot at Mench? It can save you from having to go through hundreds of resumes and automatically identify the top 10% candidates. Here's a sample Airbnb job: https://mench.com/10430 - We just launched so there is no cost.

LONGNAME, Could we add one of your job postings to our recruitment chatbot at Mench? it can save you a lot of time by automatically identifying the top 10% candidates from a mountain of resumes. Here's a sample Airbnb job: https://mench.com/10430 -We just launched so there is no cost.

LONGNAME, Could we add one of your job postings to Mench? it's a new recruitment chatbot can save you a lot of time by automatically identifying the top 10% candidates from a mountain of resumes. Here's a sample Airbnb job: https://mench.com/10430 -We just launched so there is no cost.

LONGNAME, Could we test one of your job postings on Mench? it's a cool recruitment chatbot can save you a lot of time by automatically identifying the top 10% candidates from a mountain of resumes. Here's a sample Airbnb job: https://mench.com/10430 - let me know, thanks! 🙌

{firstname}, we are looking for HR managers who would like to take part in testing our new recruitment chatbot. It can save you a lot of time by automatically identifying the top 10% candidates from a mountain of resumes. Are you interested? Let me know and I'll send details. Thanks!

{firstname}, we are looking for HR managers who would like to take part in testing our new recruitment chatbot. It speeds up hiring by automatically identifying the top 10% candidates from a mountain of resumes. Are you interested? Let me know and I'll send details. Thanks!

Hi {firstname}, we are looking for HR managers who would like to take part in testing our new recruitment chatbot. It speeds up hiring by automatically identifying the top 10% candidates from a mountain of resumes. Are you interested in trying it? Let me know and I'll send details. Thanks!

LONGNAME, we'd like to convert one of your job postings into an interactive job application over Messenger: https://mench.com/10430. Instead of having to go through hundreds of resumes, Mench automatically tells you which are the top 10% candidates. 

Hey NAME, We're making job applications suck less by turning them into conversations over Messenger. Here's a sample Airbnb job: https://mench.com/10430 - It took less than 5mins to create and it could help you find a great hire up to 3x faster. Want to know more?

Hi {firstname}, do you know why he fell in the well?... because he didn't see that well 😂. Bad jokes aside, I'm looking for an HR manager suffering from resume pile overload. If that's you, may be our friendly recruitment chatbot can help. Are you interested in seeing a demo?

Hi {firstname}, I'm Miguel from Mench. I'm looking for an HR manager suffering from resume pile overload. If that's you, may be our friendly open-source recruitment chatbot can help. It screens software engineers based on 90+ skills & identifies the top 10%. I'd love to show you how it works!

Hi {firstname}, I'm Miguel from Mench. I'm looking for an HR manager suffering from resume pile overload. If that's you, may be our friendly open-source recruitment chatbot can help. It screens software engineers based on 90+ skills & identifies the top 10%. Would you like to see a demo?

Hi {firstname}, I'm looking for an HR manager suffering from resume pile overload. If that's you, maybe our friendly open-source recruitment chatbot can help. It automatically screens software engineers based on 90+ skills & identifies the top 10%. How about a demo? - Miguel\

Hi {firstname}, I'm looking for an HR manager suffering from resume pile overload. If that's you, maybe our friendly open-source recruitment chatbot can help. It automatically screens software engineers based on 90+ skills & identifies the top 10%. Can I send you a link to see it in action?

Hi {firstname}, I'm looking for an HR manager suffering from resume pile overload. If that's you, maybe our friendly open-source recruitment chatbot can help. It automatically screens software engineers based on 90+ skills & identifies the top 10%. Can I send you a free demo?

**Comment by shervine** [comment]
Hi {firstname} my name is Miguel. I co-founded Mench, an open-source recruitment chatbot that screens software engineers based on 90+ skills & identifies the top 10%. Mench saves time & reduces hiring biases. If interested I can demo how we turn boring job postings into engaging conversations.

**Comment by shervine** [comment]
@grumo Are we still thinking of doing this along side our emails?

**Comment by grumo** [comment]
@shervine yes. I'm working on a new version for email reachout vs Linkedin
reachout.

**Comment by grumo** [comment]
@shervine we switched to cold emails for now
