### ISSUE TITLE
Make Drafting Statuses Public

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2480]
@grumo We currently have an issue when we want to mine expert content: The miner:

1. Picks the expert source they want to mine
2. Sets a new expert source status to drafting to indicate they are working on it
3. Miner adds themselves as the parent of the expert source as they are the miner
4. Miner starts creating intent notes to mine the expert source, but cannot publish any of the intent notes because the expert source status is still drafting!

To resolve this, I will make the Drafting status for intents, entities and links to be public which would then allow the miner to publish intent notes before expert source is fully mined.

**Comment by grumo** [comment]
@shervine Like this idea!
