### ISSUE TITLE
Expand "Other Intentions" Scope

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2482]
Currently, we only list featured intentions and parent intentions that are starting points.

We can expand the scope to also include:

- [x] Sibling intentions that are starting points
- [x] Child intentions that are starting points

**Comment by shervine** [comment]
@grumo Now we have a large set of recommendations at the bottom of each intent, good for both users and search engines:

https://mench.com/10399

**Comment by grumo** [comment]
Nice!
