### ISSUE TITLE
Research Skillenza

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2487]
https://skillenza.com/

- [x] Check out job application online challenge: https://skillenza.com/challenge/signeasy-online-challenge-frontend-developer-may

Prove Yourself
Join, discover, compete and stand out with Skillenza.
#ProveYourself with the skills you have.

**Comment by grumo** [comment]
<img width="778" alt="Screen Shot 2019-07-01 at 1 32 56 PM" src="https://user-images.githubusercontent.com/7246512/60465048-012ce600-9c05-11e9-83d5-3e70700959d8.png">
<img width="589" alt="Screen Shot 2019-07-01 at 1 33 08 PM" src="https://user-images.githubusercontent.com/7246512/60465051-0427d680-9c05-11e9-92ed-35a378377532.png">

**Comment by grumo** [comment]
<img width="843" alt="Screen Shot 2019-07-01 at 1 36 13 PM" src="https://user-images.githubusercontent.com/7246512/60465123-35a0a200-9c05-11e9-97dc-ff83d82ac11b.png">

**Comment by grumo** [comment]
<img width="977" alt="Screen Shot 2019-07-01 at 1 37 18 PM" src="https://user-images.githubusercontent.com/7246512/60465180-5b2dab80-9c05-11e9-93bb-68b827a41c43.png">

**Comment by shervine** [comment]
@grumo Try to always append the latest milestone to all github issues to keep track of the timing of when each issue was completed. You can do it for this one too

**Comment by grumo** [comment]
@shervine done
