### ISSUE TITLE
Company Pricing Model V1

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2488]
Based on Pivot #2485 we should setup a pricing model where we charge companies for using our software (assessment engine and educational messages).

To get things started, we can offer companies:

- First 25 users free (trial period), then it would be:
- $1/user/completed-intention which means we **only charged for users who complete the job posting (fail or pass)** which incentivizes us to iteratively work on increasing the completion rate of each intent tree, which will be aligned with our revenue model as it would help us make more money.
- We can have a weekly invoicing system where we give companies macro stats of their past week, total new candidates who completed a job posting and the total amount charged on their credit card that they had on file with us

TODO

- [x] Finalize details of MVP pricing model with @grumo 
- [x] Intent tree to explain pricing for companies
- [ ] Enable companies to manage their credit cards via Company App
- [ ] Weekly company report on candidates across all job postings
- [ ] Charge companies based on new candidates who complete their job postings
- [ ] Use [Stripe](https://stripe.com/en-ca) for payments
- [ ] Re-open non-profit bank account and setup with Strip #1967 
- [ ] Make sure Paypal business account is not charging us a monthly fee

@grumo Thoughts?

**Comment by grumo** [comment]
@shervine I propose to stick with our principle of simplicity. We don't need reivent the wheel. Have a free limited tier and 1 or 2 premium monthly recurring ones (plus discounts on yearly subscriptions)

**Comment by grumo** [comment]
@shervine we could have a based monthly recurring fee to cover access to the platform (this would help us cover our wages, servers, marketing, etc) plus an additional cost based on usage. Intercome seems to have a very successful model we can get inspiration from -> https://www.intercom.com/pricing

**Comment by grumo** [comment]
@shervine Intercom's system pricing grows with usage but it may be a bit complex to implement in the beginning. I suggest we start with a very simple pricing model and move to a more complex one - if required - once we have some actual revenues.

Unless we can make our tool 100% self-served, we will need to start looking at the $90+/month range. I don't particularly enjoy a long sales cycles with complex demos so we need to make sure our tool is dumb-proof-click-and-boom type of thing.

1. Select job template
2. Customize couple of things
3. Publish and invite candidate
4. Get results = Top 10% candidates

Must-watch video on B2B pricing models: https://www.youtube.com/watch?v=HoGj3IyHXJU

**Comment by shervine** [comment]
@grumo Based on our discussions yesterday we would price each Active job posting at $85/month which includes unlimited applicants while also offering the first 100 applicants free as a trial period. We would also offer "Fair Billing" which means we automatically determine when job postings are "active" and only charge them for the period that they are actually using it, and not during the time that they are working on building/launching the job posting.

**Comment by grumo** [comment]
@shervine sounds good. Now we need to determine how we determine "active". Maybe if the job posting doesn't receive new applicants after 1 month we would switch it to "inactive" and stop billing for that job. So at the end of each month, any jobs that are inactive for more than a month would be switched to inactive.
