### ISSUE TITLE
Analyze Coding Skill Assessment Platforms

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2492]
So we gain a better understanding of what's in the market and how their products work

- [ ] https://www.testdome.com
- [ ] https://devskiller.com
- [ ] https://www.codility.com/products/codecheck

**Comment by shervine** [comment]
@grumo By reviewing these platforms, I have the following concerns around our approach:

- Multiple-choice only: We do not have a code console but all above platforms do! The question is, can we really become the best assessment platform by just relying on multiple-choice questions? Maybe yes, but we have to really work hard to ensure that our assessments are well-balance and optimized.
- Messenger only: All above platforms offer a dedicated portal to test candidates without requiring any external apps like Messenger. If we're asking for companies to pay us, would they accept the fact that we only work on Messenger, and this would prevent some candidates (maybe the best one?!) to not take the assessment because they do not use Messenger?

The alternative approach is to pitch out platform as a mix of:

- Education
- Assessment
- Input collection

And not try to be the best in anyone, but the best in the mix of the above.

We can talk more about this tomorrow.

**Comment by grumo** [comment]
@shervine same concerns. It's hard to beat any product that has been built from the ground up to solve a specific problem. We are doing the opposite, we've built a product and now we're trying to find a problem to solve with it. It's like finding a lock and making a key to open it vs. making a key and then trying to find a lock where it fits. The first approach is always more likely to work.

**Comment by shervine** [comment]
Merging into Market Study Sheet for Software Engineering Recruitment Funnel #2494
