### ISSUE TITLE
Research programmer personas

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2506]
## Personas:

**Academic Programmer:** Candidate has spent most of their career in academia, programming as part of their Masters/PHD research. They have very high raw intellect and can use it to solve hard programming problems, but their code is idiosyncratic.

**Experienced Rusty Programmer:** Candidate has a lot of experience, and can talk in depth about different technology stacks and databases, explaining their positives and negatives with fine detail. When programming during an interview, they’re a little rusty. They usually get to the right place but it takes a while.

**Trial and Error Programmer:** Candidate writes code quickly and cleanly. Their approach seems to involve a lot of trial and error, however. They dive straight into programming problems and seem a little ad hoc but their speed enables them to ultimately solve the problems productively.

**Strong Junior Programmer:** Candidate is fresh out of college, with some internships and less than a year full time work experience. They really impress during a technical interview, have numerous side projects and impressive knowledge of computer science and programming in general. They’re well above average from other junior programmers.

**Child Prodigy Programmer:** Candidate is very young (e.g. 19 years old) and decided to go straight into work, skipping college. They’ve been programming since a very young age and are very impressive in their ability to solve hard technical problems. They’ve also been prolific with side projects and are mature for their age. It’s likely they’ll found a company in the future when they’re older.

**Product Programmer:** Candidate performs well on technical interviews and will have the respect of other engineers. They’re not motivated by solving technical problems, however. They want to think about the product, talk to customers and have an input into how product decisions are made.

**Technical Programmer:** Candidate is the inverse of the Product Programmer. They interview well and communicate clearly. But they aren’t motivated to think about the user experience or product decisions. They want to sink their teeth into hard technical problems.

**Practical Programmer:** Candidate solves practical programming problems with ease, even very abstract programs. They aren’t comfortable with computer science terminology though (e.g. data structures, algorithms) and don’t have a deep understanding of how computers work. They are strongest with ruby/python/javascript, not so much with lower level languages like C.

**Enterprise Programmer:** Candidate is strong in academic computer science (algorithms, data structures, complexity analysis), has experience, and solves technical problems well. Their working experience is with large enterprise companies (e.g. Dell/Oracle/IBM). They want to join the startup, although they don’t have experience taking ownership of projects. They program mostly in Java using an IDE such as Eclipse.

Source: https://triplebyte.com/blog/a-taxonomy-of-programmers

## Most Important Engineering Skills

- Applied problem solving
- Algorithms knowledge
- Professional code
- Communication skill
- Architecture Skill
- Low-level systems understanding
- Back-end web understanding

Source: https://triplebyte.com/blog/triplebyte-engineer-genome-project

**Comment by shervine** [comment]
@grumo To make this work I will Test Workflow for Duplicate Granchild Questions #2509
