### ISSUE TITLE
Data Protection intent

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2516]
Hi there! We would love to talk with you. Under the EU General Data Protection Regulation, we need your approval for our use of personal information (e.g. your name and email address) you may provide as we communicate:

(1) We'll store your personal information so that we can pick up the conversation if we talk later.

(2) We may send you emails to follow up on our discussion here.

(3) We may send you emails about our upcoming services and promotions.

Is this okay with you?
Yes, I Accept
No, Not Now

**Comment by shervine** [comment]
Working on this now as part of Mine Join Mench V1 #2581
