### ISSUE TITLE
Create careers page and job application trees for Mench

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#2579]
@shervine Which positions should we create Mench applications for?

Career openings tree on Mench: https://mench.com/intents/12747

- [X] Full Stack Developer ([Template](https://docs.google.com/document/d/114XIkP9oUbU1GQayMLpqRxh7N_dR9bRncIvwOTaUxb0/edit#))
- [x] Business Development Representative ([Template](https://docs.google.com/document/d/1H0Jqg3lZZDULkNVsDIxYWG6Rljg4uU_4gcVl8fp9AVE/edit#))
- [x] Lead Knowledge Miner ([Template](https://docs.google.com/document/d/1w55XFWXyB1MeOQwpXF7GYnvbu2PL87VncA3YeOzLHQk/edit#))
- [ ] Growth Hacker/Marketing ([sample 1](https://angel.co/company/bitesizehq/jobs/523330-growth-hacker))

- [ ] DevOps

Indeed Postings: https://employers.indeed.com/j#jobs

References:
- https://www.intercom.com/careers#roles

**Comment by shervine** [comment]
@grumo This has also been added to our footer to give it more visibility
