### ISSUE TITLE
Troubleshoot Server Issues [High Priority]

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#3490]
Identify the underlying cause of our server downtime and implement a resolution. https://superhost.management/ is not accessible due to some AWS configuration that happened over night. See attached EC2 server monitoring history which shows an uptick in CPU usage for an unknown reason.

**Comment by shervine** [comment]
@agustinfarinadev issue seems resolved, did you clear the disk?

**Comment by agustinfarinadev** [comment]
@shervine , I did.

**Comment by shervine** [comment]
@agustinfarinadev mentioned his Steps taken:

1. I found that the machine was running out of space. The file named /var/mail/ubuntu has size of 74 GB, which is weird.
2. Created an image of the machine for backup purpose.
3. Stopped the original machine instance. To save disk space cost, It will need to be deleted later later we confirm everything works correctly.
4. Created a new instance from the image, but attach additional disk space with size 200 GB.
5. Start the new machine instance, assign the same IP address to it, and mount the new disk to folder /mnt/new-mail.
6. Moved files /var/mail/root and var/mail/ubuntu to /mnt/new-mail.
7. Deleted folder /var/mail.
8. Create a symbolic link from /var/mail to /mnt/new-mail
9. Restart the new machine.
10. https://superhost.management/ can be accessed again
